<?xml version="1.0" encoding="UTF-8"?><testsuite name="nosetests" tests="32" errors="0" failures="1" skip="0"><testcase classname="tests.test_models.TestCustomerModel" name="test_add_a_customer" time="0.045"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_bad_update" time="0.065"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_create_a_customer" time="0.059"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_delete_a_customer" time="0.070"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_deserialize_a_customer" time="0.055"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_deserialize_bad_data" time="0.056"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_find_by_active" time="0.073"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_find_by_address" time="0.070"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_find_by_email" time="0.066"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_find_by_first_name" time="0.067"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_find_by_last_name" time="0.069"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_find_customer" time="0.061"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_repr" time="0.055"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_serialize_a_customer" time="0.063"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_suspend_a_customer" time="0.069"></testcase><testcase classname="tests.test_models.TestCustomerModel" name="test_update_a_customer" time="0.064"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_create_customer" time="0.074"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_delete_a_customer" time="0.072"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_get_customer" time="0.067"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_get_customer_list" time="0.094"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_get_customer_not_found" time="0.065"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_index" time="0.057"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_method_not_supported" time="0.060"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_query_customer_list_by_active" time="0.108"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_query_customer_list_by_address" time="0.105"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_query_customer_list_by_email" time="0.114"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_query_customer_list_by_first_name" time="0.103"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_query_customer_list_by_last_name" time="0.105"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_search_bad_data" time="0.061"><failure type="builtins.AssertionError" message="200 != 500"><![CDATA[Traceback (most recent call last):
  File "/usr/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/home/vagrant/venv/lib/python3.6/site-packages/mock/mock.py", line 1369, in patched
    return func(*newargs, **newkeywargs)
  File "/vagrant/tests/test_service.py", line 354, in test_search_bad_data
    self.assertEqual(resp.status_code, status.HTTP_500_INTERNAL_SERVER_ERROR)
  File "/usr/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python3.6/unittest/case.py", line 822, in _baseAssertEqual
    raise self.failureException(msg)
AssertionError: 200 != 500
]]></failure></testcase><testcase classname="tests.test_service.TestCustomers" name="test_suspend_customer" time="0.074"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_suspend_not_available" time="0.058"></testcase><testcase classname="tests.test_service.TestCustomers" name="test_update_customer" time="0.074"></testcase></testsuite>